version: '3'
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ps60}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-q2887628}
      POSTGRES_USER: ${POSTGRES_USER:-ps60user}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-password}
    ports:
      - "5432:5432"
volumes:
  database_data:



